---
title: "Lab3"
author: ""
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

For this project we will be performing an experiment assessing whether there are differences in flight distance between two paper airplanes designed by NASA. For details see [https://www.grc.nasa.gov/www/k-12/airplane/glidpaper.html](https://www.grc.nasa.gov/www/k-12/airplane/glidpaper.html)

To complete the experiment, please follow the directions below:

1. Flip a coin to determine which airplane you will fold and throw first. If you get `Heads`, please create airplane PA-1 ("the glider") first. If you get `Tails`, please create and throw airplane PA-2 ("the dart") first.

2. The glider can be constructed with the following [instructions: (link)](https://github.com/stat441/Labs/raw/main/Airplane1.pdf). Make sure to use two-sided printing for easiest folding. The dart can be constructed with the following [instructions: (link)](https://github.com/stat441/Labs/raw/main/Airplane2.pdf).

3. After constructing both airplanes, you make take a few practice throws, but make sure to practice evenly with both.

4. When ready, throw your airplanes in the order specified by your coin flip. Please report the distance traveled (in feet) by measuring the farthest point away where the ends.

5. For this lab, please submit your results. Specify which airplane was constructed / thrown first and the distance for each airplane. If you are inclined also consider filling out this Google Form: [https://docs.google.com/forms/d/e/1FAIpQLSf5mhVq4G25fMCGuZsttC75aCwVfHbJpjconvzgiIMv5QBXcQ/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSf5mhVq4G25fMCGuZsttC75aCwVfHbJpjconvzgiIMv5QBXcQ/viewform?usp=sf_link)

