---
title: "Lab 9"
author: " "
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Lab 9 and HW 4 will be focused on designing an in class experiment focused on paper helicopters. Our research goal will look at a range of wing length and body width combinations in a factorial experiment. You may also want to consider blocking factors.

For Lab 9, please submit a picture of a helicopter that you created using, say [https://www.wikihow.com/Create-a-Paper-Helicopter](https://www.wikihow.com/Create-a-Paper-Helicopter)


For HW 4, please complete the following checklist. You can consider Lab 9 to be our pilot study.

1. Define objectives
2. Define meaningful and measurable response
3. Diagram treatment application process for a single run
4. Identify experimental units
5. List sources of variation
6. Perform pilot runs
7. Choose experimental design (i.e. randomization)
8. Determine number of replicates required
9. Describe method(s) for data analysis
10. Timetable and budget for resources to complete experiment

